{{- if .Values.ingress.clusterIssuer.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.ingress.clusterIssuer.server }}
    email: tommy@lastcoolnameleft.com
    privateKeySecretRef:
      name: {{ .Values.ingress.clusterIssuer.name }}
    http01: {}
{{- end -}}