apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        - name: app-config
          mountPath: {{ .Values.deployment.appConfigMountPath }}
        - name: images
          mountPath: {{ .Values.deployment.imagesMountPath }}
        env:
        - name: CI_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: phippy
              key: CI_BASE_URL

# This makes A LOT of log entries.  Slowing my roll for now            
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 80
#          initialDelaySeconds: 1
#          periodSeconds: 60
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#          initialDelaySeconds: 1
#          periodSeconds: 60


        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
