# Generated by Django 2.1 on 2018-12-23 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('toy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128)),
                ('comments', models.TextField(blank=True, default=None)),
                ('approved', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ToyLocation',
            fields=[
                ('toy_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('flickr_photo_id', models.BigIntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('approved', models.CharField(blank=True, max_length=1, null=True)),
                ('toy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Toy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToyLocationLink',
            fields=[
                ('toy_location_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('toy_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='track.ToyLocation')),
            ],
        ),
        migrations.CreateModel(
            name='ToyLocationPhoto',
            fields=[
                ('toy_location_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('flickr_photo_id', models.BigIntegerField(blank=True, null=True)),
                ('flickr_thumbnail_url', models.TextField(blank=True, null=True)),
                ('toy_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='track.ToyLocation')),
            ],
        ),
    ]
